### ISSUE TITLE
Does not recognize simpledimensions dimensions (1.10.2)

### ISSUE THREAD

**Issue by krisboyce** [lumien231/Dimension-Rules#1]
if (worldObj.provider.getDimensionType().getId() == 0) this line is true for simpledimensions dimensions. I'm not sure if this is an issue on your side or the dimension provider's.

**Comment by krisboyce** [comment]
@lumien231 So, I wanted to go ahead and fix this myself but it looks like the source here is for 1.9. Do you have an updated source?

**Comment by lumien231** [comment]
Updated the Repo to the 1.9.4 code, didn't have to make any changes for 1.10.
